story1/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'story1'

urlpatterns = [
    path('profile/', views.profile, name='story1_profile' ),
    path('', views.index, name='index'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'story6'

urlpatterns = [
    path('kegiatan', views.kegiatan, name='story6_kegiatan' ), 
    path('form_kegiatan', views.form_kegiatan, name='story6_form_kegiatan' ),
    path('form_anggota', views.form_anggota, name='story6_form_anggota' ),
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1.urls')),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
     path('story9/', include('story9.urls')),
]

story6/models.py
from django.db import models

# Create your models here.

class KegiatanModel(models.Model):
    nama_kegiatan = models.CharField(max_length=50)
    deskripsi = models.TextField()
    def __str__(self):
        return "{}".format(self.nama_kegiatan)

class AnggotaModel(models.Model):
    nama_anggota = models.CharField(max_length=50)
    kegiatan = models.ForeignKey(KegiatanModel, on_delete=models.CASCADE)
    def __str__(self):
        return "{}".format(self.nama_anggota)

story6/forms.py
from django import forms

from .models import KegiatanModel
from .models import AnggotaModel 

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = KegiatanModel
        fields = "__all__"

class AnggotaForm(forms.ModelForm):
    class Meta:
        model = AnggotaModel
        fields = "__all__"

story6/views.py
from django.shortcuts import render,redirect

from .forms import KegiatanForm, AnggotaForm

from .models import KegiatanModel, AnggotaModel

# Create your views here.

def kegiatan(request):
    kegiatans = KegiatanModel.objects.all()
    anggotas = AnggotaModel.objects.all()
    
    context = {
        'kegiatans': kegiatans,
        'anggotas' : anggotas,  
    }
    return render(request, "kegiatan.html", context) 

def form_kegiatan(request):
    kegiatan_form = KegiatanForm()
    if request.method == 'POST':
        form = KegiatanForm(request.POST)
        form.save()
    
    context = {
        'data_form': kegiatan_form
    }
    return render(request, "form_kegiatan.html", context)

def form_anggota(request):
    anggota_form = AnggotaForm()
    
    if request.method == 'POST':
        form = AnggotaForm(request.POST)
        form.save()
    
    context = {
        'data_form': anggota_form
    }
    return render(request, "form_anggota.html", context)

story6/templates/form_anggota.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/kegiatan.css' %}" type="text/css">
{% endblock css %}

{% block content %}

<ul>
    <h1 style="text-align: center;"> Tambah Anggota </h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{data_form.as_table}}
        </table>
        <br>
        <button type="submit" class="btn btn-primary" style="background-color: #699cb3;">Tambah Anggota</button>
    </form>
    <br>
    <a href="{% url 'story6:story6_kegiatan' %}" class="btn btn-primary" style="background-color: #347893; align-items: center;">Lihat Daftar Kegiatan</a>
    
</ul>




{% endblock content %}

story6/templates/form_kegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/kegiatan.css' %}" type="text/css">
{% endblock css %}

{% block content %}

<ul>
    <h1 style="text-align: center;"> Tambah Kegiatan </h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{data_form.as_table}}
        </table>
        <br>
        <button type="submit" class="btn btn-primary" style="background-color: #699cb3;">Tambah Kegiatan</button>
    </form>
    <br>

    <a href="{% url 'story6:story6_kegiatan' %}" class="btn btn-primary" style="background-color: #347893; align-items: center;">Lihat Daftar Kegiatan</a>

</ul>




{% endblock content %}

story6/templates/kegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/kegiatan.css' %}" />
{% endblock css %}

{% block content %}
<h1 style="text-align: center;"> Kegiatan </h1>

<br>
<br>

<a href="{% url 'story6:story6_form_kegiatan' %}" class="btn btn-primary" style="background-color: #f9e4b7; align-items: center; color: #cf0107;">Tambah Kegiatan</a>

<br>
<br>
{% for kegiatan in kegiatans %}
    <div class="card" style="width: 18rem; float: left; ">
        <div class="card-body">
        <h3 class="card-title" style="background-color:#f9e4b7; text-align: center;color: #cf0107;">{{kegiatan.nama_kegiatan}}</h3>
        <p class="card-text" style="text-align: center;">{{kegiatan.deskripsi}}</p>
        <p class="card-text" style="text-align: center;">Peserta : </p>
        {% for anggota in anggotas %}
            {% if anggota.kegiatan.nama_kegiatan == kegiatan.nama_kegiatan %}
                <p class="card-text" style="text-align: center;">{{anggota.nama_anggota}}</p>
            {% else %}

            {% endif %}
        {% endfor %}
        <a href="{% url 'story6:story6_form_anggota' %}" class="btn btn-primary" style="background-color:#f9e4b7; display: flex; justify-content: center;color: #cf0107;"> Tambah Anggota</a>
        </div>
    </div>

{% endfor %}


{% endblock content %}