story1/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'story1'

urlpatterns = [
    path('profile/', views.profile, name='story1_profile' ),
    path('', views.index, name='index'),
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'story5'

urlpatterns = [
    path('matkul', views.matkul, name='story5_matkul' ), 
    path('jadwal', views.jadwal, name='story5_jadwal' ), 
    path('delete/<int:delete_id>', views.delete, name='delete'),
    path('detail/<int:id_matkul>', views.detail, name ='detail'),
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1.urls')),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
     path('story9/', include('story9.urls')),
]

story5/models.py
from django.db import models

# Create your models here.
class MatkulModel(models.Model):
    nama_Mata_Kuliah = models.CharField(max_length=100)
    pengajar = models.CharField(max_length=100)
    SKS = models.IntegerField()
    PILIHAN = {
        ('Gasal', 'Gasal'),
        ('Genap', 'Genap')
    }
    Semester = models.CharField(choices=PILIHAN, max_length=5)
    TAHUN = {
        ('2019', '2019'),
        ('2020', '2020')
    }
    Tahun = models.CharField(choices=TAHUN,max_length=5)
    Deskripsi = models.TextField(max_length = 500)
    Ruang_kelas = models.CharField(max_length =10)

    def __str__(self):
        return "{}.{}".format(self.id, self.nama_Mata_Kuliah)

story5/forms.py
from django import forms

from .models import MatkulModel
class MatkulForm(forms.ModelForm):
    class Meta:
        model = MatkulModel
        fields = "__all__"

# class MatkulForm(forms.Form):
#     # python data type

#     nama_Mata_Kuliah = forms.CharField(max_length = 100)
#     pengajar = forms.CharField(max_length = 100)
#     SKS = forms.IntegerField()

#     PILIHAN = {
#         ('Gasal', 'Gasal'),
#         ('Genap', 'Genap')
#     }
#     Semester = forms.ChoiceField(choices=PILIHAN)
#     TAHUN = {
#         ('2019', '2019'),
#         ('2020', '2020')
#     }
#     Tahun = forms.ChoiceField(choices=TAHUN)
#     Deskripsi = forms.CharField(widget=forms.Textarea, max_length=500)
#     Ruang_kelas = forms.CharField(max_length=10)

story5/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect

# Create your views here.

"""
def index(request):
    return render(request,"index.html")
"""
from .forms import MatkulForm
from .models import MatkulModel

# Story 5

def matkul(request):
    matkuls = MatkulModel.objects.all()
    matkul_form = MatkulForm()
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        form.save()
    #    MatkulModel.objects.create(
    #         nama_Mata_Kuliah = request.POST['nama_Mata_Kuliah'],
    #         pengajar = request.POST['pengajar'],
    #         SKS = request.POST['SKS'],
    #         Semester = request.POST['Semester'],
    #         Tahun = request.POST['Tahun'],
    #         Deskripsi = request.POST['Deskripsi'],
    #         Ruang_kelas = request.POST['Ruang_kelas']
    #     )
    context = {
        'data_form': matkul_form,
        'matkuls':matkuls
    }
    return render(request, "matkul.html", context)

def delete(request,delete_id):
    MatkulModel.objects.filter(id=delete_id).delete()
    return redirect('story5:story5_matkul')

def jadwal(request):
    matkuls = MatkulModel.objects.all()
    matkul_form = MatkulForm()
    
    context = {
        'data_form': matkul_form,
        'matkuls':matkuls
    }

    return render(request, "jadwal.html", context) 

def detail(request, id_matkul):
    matkuls = MatkulModel.objects.get(id=id_matkul)
    
    context = {
        'matkuls':matkuls
    }
    return render(request, "detail_matkul.html", context)

def index(request):
    return render(request, "story1/index.html") 

story5/templates/detail_matkul.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/matkul.css' %}" type="text/css">
{% endblock css %}

{% block content %}


<ul>
<h2 style="background-color:#BF5B04; color: white; text-align: center;"> &nbsp; &nbsp; M A T A &nbsp; K U L I A H </p>
<h2 >{{matkuls.nama_Mata_Kuliah}}</h2>
<p> Diajar oleh {{matkuls.pengajar}} </p>
<p> {{matkuls.SKS}} SKS </p>
<p> Semester {{matkuls.Semester}} Tahun {{matkuls.Tahun}} </p>
<p> Ruang {{matkuls.Ruang_kelas}} </p>
<p style="background-color:#BF5B04; color: white; text-align: center;"> &nbsp; &nbsp; D E S K R I P S I </p>
<p> {{matkuls.Deskripsi}} </p>


</ul>






{% endblock content %}

story5/templates/jadwal.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/matkul.css' %}" type="text/css">
{% endblock css %}

{% block content %}


<ul>
<p> D A F T A R &nbsp; M A T A &nbsp; K U L I A H </p>
    <!-- {% for matkul in matkuls %}
        <h2>{{matkul.nama_Mata_Kuliah}}</h2>
        <p> Diajar oleh {{matkul.pengajar}}</p>
        <p>{{matkul.SKS}} SKS</p>
    {% endfor %} -->

    <table class="table">
        <thead style="background-color:#BF5B04; color: white;">
          <tr>
            <th scope="col">No</th>
            <th scope="col">Mata Kuliah</th>
            <th scope="col">Pengajar</th>
            <th scope="col">SKS</th>
            <th scope="col">Semester</th>
            <th scope="col">Tahun</th>
            <th scope="col">Deskripsi</th>
            <th scope="col">Ruang</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
            {% for matkul in matkuls %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{matkul.nama_Mata_Kuliah}}</td>
            <td>{{matkul.pengajar}}</td>
            <td>{{matkul.SKS}}</td>
            <td>{{matkul.Semester}}</td>
            <td>{{matkul.Tahun}}</td>
            <td >{{matkul.Deskripsi}}</td>
            <td>{{matkul.Ruang_kelas}}</td>
            <td> <a class="btn btn-warning" href="{%url 'story5:delete' matkul.id %}"> Delete</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      
</ul>






{% endblock content %}

story5/templates/matkul.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/matkul.css' %}" type="text/css">
{% endblock css %}

{% block content %}



<ul>
    <p> T A M B A H K A N &nbsp; M A T A &nbsp; K U L I A H  </p>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{data_form.as_table}}
        </table>
        <br>
        <button type="submit" class="btn btn-primary" style="background-color:#f9e4b7; color: #cf0107;">S U B M I T</button>
    </form>
</ul>

<br>
<br>
<br>

<ul>
<p> D A F T A R &nbsp; M A T A &nbsp; K U L I A H </p>
<a class="btn btn-primary" style="background-color:#f9e4b7; color: #cf0107;"href= "{%url 'story5:story5_jadwal' %}"> J A D W A L </a>
    

    <table class="table">
        <thead style="background-color:#f9e4b7; color: #cf0107;">
          <tr>
            <th scope="col">No</th>
            <th scope="col">Mata Kuliah</th>
            <th scope="col">Detail</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
            {% for matkul in matkuls %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{matkul}}</td>
            <td> <a class="btn btn-primary" href="{%url 'story5:detail' matkul.id %}"> Detail</a></td>
            <td> <a class="btn btn-warning" href="{%url 'story5:delete' matkul.id %}"> Delete</a></td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
      
</ul>






{% endblock content %}