story1/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'story1'

urlpatterns = [
    path('profile/', views.profile, name='story1_profile' ),
    path('', views.index, name='index'),
]

story3/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'story3'

urlpatterns = [
    path('hobby', views.hobby, name='story3_hobby' ), 
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'story5'

urlpatterns = [
    path('matkul', views.matkul, name='story5_matkul' ), 
    path('jadwal', views.jadwal, name='story5_jadwal' ), 
    path('delete/<int:delete_id>', views.delete, name='delete'),
    path('detail/<int:id_matkul>', views.detail, name ='detail'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'story6'

urlpatterns = [
    path('kegiatan', views.kegiatan, name='story6_kegiatan' ), 
    path('form_kegiatan', views.form_kegiatan, name='story6_form_kegiatan' ),
    path('form_anggota', views.form_anggota, name='story6_form_anggota' ),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'story7'

urlpatterns = [
    path('informasi', views.accordion, name='story7_accordion' ), 
   
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1.urls')),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
     path('story9/', include('story9.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% block meta %}
  <!-- Title Tag -->
  {% endblock meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <title>{% block title %}Nadia Sabrina{% endblock title %}</title>
    {% block css %}
    {% endblock css %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #F9E4b7;">
        <a class="navbar-brand" href="#" style="color: #cf0107; font-weight: 700;"> H E L L O ! </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'story1:index' %}" style="color: #cf0107; font-weight: 700;">Home <span class="sr-only">(current)</span></a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li> -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #cf0107; font-weight: 700;">
                Projects
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #F9E4b7;">
                <a class="dropdown-item" href="{% url 'story5:story5_matkul' %}" style="color: #cf0107; font-weight: 700;">Story 5</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'story6:story6_kegiatan' %}" style="color: #cf0107; font-weight: 700;">Story 6</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'story7:story7_accordion' %}" style="color: #cf0107; font-weight: 700;">Story 7</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'story8:story8_bookfinder' %}" style="color: #cf0107; font-weight: 700;">Story 8</a>
              </div>
            </li>
            
          </ul>
          {% if user.is_authenticated %}
          <h5 style="margin-top: 0.8%;"> Hello, {{request.user.get_short_name}} &nbsp;</h5>
          <a class="nav-link" href="{% url 'story9:story9_logout' %}" style="color: #cf0107; font-weight: 700;">Logout<span class="sr-only">(current)</span></a>


          {% else %}
          <a class="nav-link" href="{% url 'story9:story9_login' %}" style="color: #cf0107; font-weight: 700;">Login<span class="sr-only">(current)</span></a>
          <a class="nav-link" href="{% url 'story9:story9_register' %}" style="color: #cf0107; font-weight: 700;">Register<span class="sr-only">(current)</span></a>

          {% endif %}
          <h4 style="background-color:#f9e4b7; color: #cf0107; margin-top: 0.5%;" >  • by nadiasabrina </h4>
        </div>
      </nav>

    <!-- <div class="header">
        <a href="{% url 'story1:index' %}" style="text-decoration: none; color:black;">
            <h1 style="text-align:center"> N A D I A • S A B R I N A </h1>
        </a>   
    </div> -->

     <!-- BUAT SIDE NAV
  
    <script>

    /* Set the width of the side navigation to
    250px */ 
    
    function openNav() {
     document.getElementById("mySidenav")
     .style.width="250px";
    }
    
    function closeNav() {
     document.getElementById("mySidenav")
     .style.width = "0";
    }
    </script>
  
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a  style="text-align:center; background-color: #DDB247" href="{% url 'story1:story1_profile' %}">Profile</a>
      <a  style="text-align:center; background-color: #DDB247" href="{% url 'story3:story3_hobby' %}">Hobby</a>
      <a style="text-align: center; background-color: #DDB247;" href="{% url 'story5:story5_matkul' %}">Mata Kuliah</a>
      <a style="text-align: center; background-color: #DDB247;" href="{% url 'story6:story6_kegiatan' %}">Kegiatan</a>
    </div>
 
    <span style="font-size:70px; cursor:pointer"onclick="openNav()">☰</span> -->
    

    {% block content %}{% endblock content %}

    {% block script %}{% endblock script %}
</body>
</html>