story1/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'story1'

urlpatterns = [
    path('profile/', views.profile, name='story1_profile' ),
    path('', views.index, name='index'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'story9'

urlpatterns = [
    path('login', views.loginpage, name='story9_login'), 
    path('register', views.register, name='story9_register'),  
    path('logout', views.logoutUser, name='story9_logout'),  
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1.urls')),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
     path('story9/', include('story9.urls')),
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1']

class AuthenticateForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password1']

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import CreateUserForm
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.contrib.auth.hashers import make_password
import json


# Create your views here.
def loginpage(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST) 
        if form.is_valid():
            user = form.get_user()
            login(request, user)    
            return redirect('story1:index')
    else: 
        form = AuthenticationForm() 
    context = {"form" : form}
    return render(request, "login.html", context) 

# def loginpage(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password1')
#         # user = authenticate(request, username=username, password=password)
#         # login(request, username, password)
#         user = authenticate(request, username=username, password=password)
#         login(request, user)
        
#     #     if user is not None:
#     #         login(request,user)
#     #         return redirect('story1:index')
#     #     else:
#     #         HttpResponse("Incorrect username or password")
    
#     return render(request, "login.html") 

def register(request):
    form = CreateUserForm();
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            return redirect('story9:story9_login')
    context = {"form" : form}

    return render(request, "register.html", context) 

def logoutUser(request):
    logout(request)
    return redirect('story1:index')

story9/templates/login.html
{% extends 'base.html' %}
{% load static %}
 
{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock css %}
 
{% block content %}

<div class="card" style="width: 35rem; height: 20rem;">
    <div class="card-body" >
      <h5 class="card-title" style="text-align: center; color: #f9e4b7; font-weight: 800; font-size: x-large;"> Knock-knock! Who's there? </h5>
      <br>
      <div style="color: #f9e4b7; text-align: center;">
        <form method="POST" action="">
          {% csrf_token %}
          <table style="align-items: center; margin-left: 20%; align-items: center; border-spacing: 3cm;">
            <tr>
              <td style="text-align: left;">{{form.username.label}}  </td>
              <td>{{form.username}} </td>
            </tr>
            <tr>
              <td style="text-align: left;">{{form.password.label}}  </td>
              <td>{{form.password}} </td>
            </tr>
            
          </table>
          <br>
          <button type="submit" class="btn btn-primary" style="background-color: #f9e4b7; color: #cf0107; width: 40%;">Login</button>
        </form>
        <br>
        {% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		

        Don't have an account? &nbsp; <a href="{% url 'story9:story9_register' %}" style="color: #f9e4b7;"> Register </a>
        <br>

      </div>
    </div>
</div>




{% endblock content %}
 
{% block script %}


{% endblock %}

story9/templates/register.html
{% extends 'base.html' %}
{% load static %}
 
{% block css %}
<link rel="stylesheet" href="{% static 'css/register.css' %}" />
{% endblock css %}
 
{% block content %}

<!-- <form method="POST" action="">
    {% csrf_token %}
    {{form.as_p}}
<input type="submit"> </input>
</form> -->

<div class="card" style="width: 32rem; height: 25rem;">
    <div class="card-body" >
      <h5 class="card-title" style="text-align: center; color: #f9e4b7; font-weight: 800; font-size: x-large;"> Join our little clique </h5>
      <br>
      <div style="color: #f9e4b7; text-align: center;">
        <form method="POST" action="">
          {% csrf_token %}
          <table style="align-items: center; margin-left: 10%;">
            <tr>
              <td style="text-align: left;">{{form.username.label}}  </td>
              <td>{{form.username}} </td>
            </tr>
            <tr>
              <td style="text-align: left;">{{form.first_name.label}}  </td>
              <td>{{form.first_name}} </td>
            </tr>
            <tr>
              <td style="text-align: left;">{{form.last_name.label}}  </td>
              <td>{{form.last_name}} </td>
            </tr>
            <tr>
              <td style="text-align: left;">{{form.email.label}}  </td>
              <td>{{form.email}} </td>
            </tr>
            <tr>
              <td style="text-align: left;">{{form.password1.label}}  </td>
              <td>{{form.password1}} </td>
            </tr>
            <tr>
              <td style="text-align: left;">{{form.password2.label}}  </td>
              <td>{{form.password2}} </td>

            </tr>
            
          </table>
          <br>
            
            <button type="submit" class="btn btn-primary" style="background-color: #f9e4b7; color: #cf0107; width: 60%;">Register</button>
            <br>
            Already have an account? &nbsp; <a href="{% url 'story9:story9_login' %}" style="color: #f9e4b7;"> Login</a>
            <br>
        </form>
        {{form.errors}}
      </div>
    </div>
</div>
  


{% endblock content %}
 
{% block script %}


{% endblock %}